// This file was auto-generated by the integration script.
// To make changes, edit the individual components in the "@/components/landing" directory.
'use client'; // Required for hooks like useState in FaqSection

import React from 'react';

// Import all the newly created landing page components
import CtaButton from '@/components/landing/CtaButton';
import Header from '@/components/landing/Header';
import HeroSection from '@/components/landing/HeroSection';
import PartnerSection from '@/components/landing/PartnerSection';
import SwitchSection from '@/components/landing/SwitchSection';
import ExpertSection from '@/components/landing/ExpertSection';
import TestimonialSection from '@/components/landing/TestimonialSection';
import ProjectsSection from '@/components/landing/ProjectsSection';
import WorkflowSection from '@/components/landing/WorkflowSection';
import FaqSection from '@/components/landing/FaqSection';
import InterestSection from '@/components/landing/InterestSection';
import Footer from '@/components/landing/Footer';

// The main home page component that assembles the entire page
export default function HomePage() {
  return (
    <div className="bg-white font-sans text-gray-800 antialiased">
      <div className="container mx-auto px-6">
        <Header />
        <main>
          <HeroSection />
          <PartnerSection />
          <SwitchSection />
          <ExpertSection />
          <TestimonialSection />
          <div className="text-center py-12">
            <CtaButton text="Get a free consultation" />
          </div>
          <ProjectsSection />
          <WorkflowSection />
          <FaqSection />
          <InterestSection />
        </main>
        <Footer />
      </div>
    </div>
  );
}
